// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxZhA3ReJy3Jb2K8Hm7hP0-l6ZpbkLqc',
    appId: '1:812399268181:web:d82203ec22ceb5abc69fdc',
    messagingSenderId: '812399268181',
    projectId: 'otp-page-32a87',
    authDomain: 'otp-page-32a87.firebaseapp.com',
    storageBucket: 'otp-page-32a87.appspot.com',
    measurementId: 'G-3XBTLW4DBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFuWBUC2YMKdj3wtDAgEfEP2GEV1mIUn8',
    appId: '1:812399268181:android:20f5733d971c29bec69fdc',
    messagingSenderId: '812399268181',
    projectId: 'otp-page-32a87',
    storageBucket: 'otp-page-32a87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJKosDD7ZstTUU1h6ZjTDd5EZWYOjyhzo',
    appId: '1:812399268181:ios:77a0a3f07505f412c69fdc',
    messagingSenderId: '812399268181',
    projectId: 'otp-page-32a87',
    storageBucket: 'otp-page-32a87.appspot.com',
    iosBundleId: 'com.example.otpPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJKosDD7ZstTUU1h6ZjTDd5EZWYOjyhzo',
    appId: '1:812399268181:ios:77a0a3f07505f412c69fdc',
    messagingSenderId: '812399268181',
    projectId: 'otp-page-32a87',
    storageBucket: 'otp-page-32a87.appspot.com',
    iosBundleId: 'com.example.otpPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsxZhA3ReJy3Jb2K8Hm7hP0-l6ZpbkLqc',
    appId: '1:812399268181:web:b8faaaf301726ef4c69fdc',
    messagingSenderId: '812399268181',
    projectId: 'otp-page-32a87',
    authDomain: 'otp-page-32a87.firebaseapp.com',
    storageBucket: 'otp-page-32a87.appspot.com',
    measurementId: 'G-2NGRNN4GKP',
  );
}
